### PR TITLE
Removing stale keys

### PR DESCRIPTION
**Pull request by Abby-Wheelis**
This is the translate - side PR for the changes in [e-mission-phone#1008](https://github.com/e-mission/e-mission-phone/pull/1008), like that PR, I want to test these files against as many differing configs as I can to ensure that I haven't removed keys that are still in use

### CODE REVIEW

**Comment by Abby-Wheelis** [comment]
> @Abby-Wheelis the configurations don't really affect the translations, although they will affect the screens available. I skimmed through and most of them do in fact appear to be obsolete. Can do a more close check once you think you have everything in here

Are the translations from these json files used anywhere that's not in the phone repo? I remember some things that might have been admin dashboard related, and there were also things related to the dashboard game that I didn't see in phone, but I wasn't sure if there were some versions of the app out there that relied on them.

**Comment by Abby-Wheelis** [comment]
We talked about this in a call today, and now I went through with removing all keys in this repo that aren't used in `e-mission-phone` on `framework_migration_prep` (our active development branch) anymore. 

I also merged in upstream updates to Lao so that we maintain the most up-to-date translations as we are in the process of getting those ironed out for the upcoming release.

**Comment by shankari** [comment]
just align this with https://github.com/e-mission/e-mission-phone/pull/1008

**Comment by Abby-Wheelis** [comment]
This should now be aligned with the phone PR, found some mistakes there while aligning them, taking care of those in [https://github.com/e-mission/e-mission-phone/pull/1017](https://github.com/e-mission/e-mission-phone/pull/1017)

**Review by shankari — APPROVED** [review]

**Pull request merged**
